spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates/
    
    

  mvc:
    static-path-pattern: /static/**
    
server: 
  tomcat:
    uri-encoding: UTF-8
  port: 8081
        
#CA supplier(eqianbao)
hfq: 
  ca:
    supplier:
      eqb:
        projectId: 1111563517
        projectSecret: 95439b0863c241c63a861b87d1e647b7
        apisUrl: http://121.40.164.61:8080/tgmonitor/rest/app!getAPIInfo2
